### ISSUE TITLE
give working example

### ISSUE THREAD

**Issue by sstidl** [Rhosys/openapi-model-validator.js#3]
I was trying to get behind the usage of your module but failed.

could you give a working example using a public service like the petshop from swagger.io
https://petstore.swagger.io/

this would help to understand what your code does.

thank you very much
steve

**Comment by wparad** [comment]
I've added an example here: https://github.com/Rhosys/openapi-data-validator.js/blob/release/2.0/examples/petstore.js

Hopefully this helps to resolve any of the issues you've been having. If you are getting an error somewhere, feel free to add it to this issue an we can reopen it.

For easy reference here's an example which throws an error:
```js
async function failsValidation() {
  const newRequest = {
    // Method
    method: 'GET',
    // Matched openapi specification generic route
    route: '/pets/{petId}',

    // Invalid path parameters, missing expected `petId` in the path, so this will cause an error.
    path: { otherParameterNotPetId: 'my-first-cat' }
  };

  try {
    await validator(newRequest);
  } catch (error) {
    console.log(error.message);
    // Bad Request: request.path must have required property 'petId', request.path must NOT have additional properties

    console.log(error.errors);
    /*
    [
      {
        path: '.path.petId',
        message: "must have required property 'petId'",
        fullMessage: 'missing required property request.path.petId'
      },
      {
        path: '.path.otherParameterNotPetId',
        message: 'must NOT have additional properties',
        fullMessage: "request.path must NOT have additional property: 'otherParameterNotPetId'"
      }
    ]
    */
  }
}
```

**Comment by sstidl** [comment]
Thank you for the example!

Now I understand. I thought your code can use the live service when validating the API. 
My use-case would be that I call the API and validate the response if it matches the schema in the OpenAPI definition.

**Comment by wparad** [comment]
This code is definitely for the service to run, i.e. validating client requests.

You wat to validate server responses...why? They're always right, right? Or did I misunderstand
